---
layout: post
title: 石洞
baseurl: ""
markdown: kramdown
plugins:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 20
paginate_path: "/:num/"
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
permalink: pretty
